/** UI copy only. User content and saved model results are never translated implicitly. */
export type Locale = 'en' | 'es'
export const EN: Record<string, string> = {
  'Trabajo': 'Work', 'Personal': 'Personal', 'Casa': 'Home', 'Social': 'Social',
  'Una conversación pendiente...': 'A conversation I need to have...',
  'Hay una conversación pendiente con': 'I need to have a conversation with',
  'Algo que me preocupa...': 'Something on my mind...',
  'Tengo atorado resolver': 'I am stuck trying to resolve',
  'Cargas acumuladas...': 'Too much on my plate...',
  'Siento que tengo que hacer mil cosas hoy, en especial': 'I feel like I have a thousand things to do today, especially',
  'El dictado necesita HTTPS o localhost. Puedes escribir tu lista.': 'Voice input needs a secure connection. You can type your list.',
  'No se habilitó el micrófono. Puedes seguir escribiendo.': 'The microphone was not enabled. You can keep typing.',
  'No se pudo continuar el dictado. Lo escrito sigue aquí.': 'Voice input stopped. Your text is still here.',
  'No se pudo abrir el micrófono. Puedes escribir tu lista.': 'The microphone could not start. You can type your list.',
  'Tu texto sigue completo. Para añadir esta sugerencia, deja un poco de espacio o continúa con lo escrito.': 'Your text is intact. Make some room to add this suggestion, or continue with what you wrote.',
  'Puedes empezar con un solo pendiente.': 'You can start with just one thing.',
  'No llegó una respuesta completa. Tu lista sigue aquí; puedes intentarlo otra vez.': 'The response did not finish. Your list is still here; you can try again.',
  'Mis pendientes': 'My tasks', 'La mesa libre': 'A clear desk',
  'Suelta lo que traes': 'Let out what is', 'en la cabeza.': 'on your mind.',
  'Escríbelo o cuéntamelo como te salga. Sin orden, sin juzgar; luego decidimos qué merece espacio.': 'Write it or say it however it comes. No sorting, no judgment; then decide what deserves your attention.',
  'Sugerencias rápidas': 'Quick prompts', '¿Qué tienes en la cabeza?': 'What is on your mind?',
  'Sugerencias activas': 'Active prompts', 'Eliminar sugerencia': 'Remove prompt',
  'Continúa tu pensamiento aquí...': 'Continue your thought here...',
  '¿Qué tienes en la cabeza? Deja caer tareas, compromisos o pensamientos sueltos...': 'What is on your mind? Drop in tasks, commitments, or loose thoughts...',
  'Escuchando con calma…': 'Listening…', 'Habla a tu propio ritmo. Sin prisas.': 'Speak at your own pace. No rush.',
  'Listo': 'Done', 'palabras': 'words', '· La mesa sostiene todo lo que pongas': '· There is room for everything on your mind',
  'Sigue escribiendo sin ordenar. Domi te ayuda después.': 'Keep writing without sorting. Domi will help next.',
  'Tómate tu tiempo. No hay límite.': 'Take your time. There is no rush.',
  'Terminar dictado': 'Stop voice input', 'Hablar': 'Speak', 'Aclarando la mesa…': 'Making room…',
  'Encontrar una cosa': 'Find one thing',
  'El dictado no está disponible en este navegador. Puedes escribir.': 'Voice input is not available in this browser. You can type.',
  'Domi está repartiendo tus pendientes en las cuatro bandejas…': 'Domi is sorting your tasks into four trays…',
  'Primero alivio, después capacidad de actuar. Nunca examen.': 'First relief, then room to act. Never a test.',
  'Error al iniciar investigación': 'Could not start research', 'Error de conexión': 'Connection error',
  '¿Algo te detiene en esta área?': 'Something holding you back here?',
  'Ej. ¿Cómo asigno una IP estática en Render?': 'E.g. How do I publish a static site on Render?',
  'Aclarar con investigación en segundo plano': 'Find answers with background research', 'Aclarar': 'Research',
  'Tus bandejas': 'Your trays', 'Cada pendiente en su lugar.': 'A place for every task.',
  'Puedes cambiar cualquiera de bandeja. Tú eliges por dónde empezar.': 'Move tasks between trays. You choose where to start.',
  'Tu punto de partida': 'Your starting point', 'Modo Momentum · Acción Inmediata': 'Momentum mode · Start here',
  'Una sola cosa a la vez': 'One thing at a time',
  'Elegida por Domi para romper la inercia y poner tu día en movimiento.': 'Suggested by Domi to help you get moving.',
  'Primer movimiento ·': 'First move ·', 'min estimados': 'min estimated',
  'Hacerla más pequeña (': 'Break it down (', 'micro-pasos disponibles)': 'small steps available)',
  'Arrancar en Dominio': 'Start focusing', 'Un solo toque. La misma tarea, sin empezar de nuevo.': 'One tap. The same task, without starting over.',
  'Los micro-pasos se están preparando en segundo plano. Ya puedes arrancar.': 'Small steps are being prepared in the background. You can start now.',
  'Los micro-pasos no llegaron.': 'The small steps did not arrive.', 'Reintentar pasos': 'Retry steps',
  'La mesa está libre.': 'Your desk is clear.', 'Lo que terminaste sigue disponible abajo.': 'Your completed tasks are still available below.',
  'Elegida': 'Selected', 'Mover a': 'Move to', 'Mesa libre en': 'All clear in',
  'pendiente terminado': 'completed task', 'pendientes terminados': 'completed tasks',
  'Añadir otro vaciado': 'Add another brain dump', 'pendientes · avance guardado en este navegador': 'tasks · progress saved in this browser',
  'No se pudo abrir la investigación.': 'Could not start the research.',
  'No se pudo confirmar el envío. No se ha repetido la petición.': 'Submission could not be confirmed. The request has not been repeated.',
  'Dominio · una cosa en movimiento': 'Focus · one thing in motion',
  'Una cosa menos en la mesa': 'One less thing on your desk', 'Sigue con esta acción': 'Stay with this action',
  'Hecho.': 'Done.', 'Registraste': 'You logged', 'en esta sesión. Tu tarea quedó marcada como terminada.': 'in this session. Your task is marked complete.',
  'Volver a la mesa': 'Back to your desk', 'Ahora · paso': 'Now · step', 'de': 'of',
  'Los pasos están marcados. Tú decides cuándo está terminada la tarea.': 'The steps are checked off. You decide when the task is complete.',
  'Puedes empezar. Los pasos llegarán aquí sin interrumpir tu sesión.': 'You can start. The steps will arrive here without interrupting your session.',
  'Trabaja en esta tarea a tu ritmo.': 'Work on this task at your own pace.',
  'Sesión en pausa': 'Session paused', 'Tiempo transcurrido': 'Elapsed time', 'Oculto': 'Hidden',
  'Reanudar': 'Resume', 'Pausar': 'Pause', 'Nuevo tramo': 'New session',
  'Registrando tiempo con calma, sin cuenta regresiva.': 'Keeping time gently, without a countdown.',
  'Micro-pasos de apoyo': 'Small steps to help', 'Los pasos no llegaron.': 'The steps did not arrive.',
  'Completé esta acción': 'I completed this action', 'Terminé esta tarea': 'I finished this task',
  'Parar por hoy': 'Stop for today', 'Ya terminé la tarea completa': 'I finished the whole task',
  'Abrir investigación guardada': 'Open saved research', 'Pedir otra investigación': 'Start another research request',
  '¿Qué te frena?': 'What is holding you back?',
  'Describe qué necesitas saber o qué te impide avanzar...': 'Describe what you need to know or what is holding you back...',
  'La nueva consulta sustituirá el acceso a la investigación anterior en tus bandejas.': 'The new request will replace the research link currently shown in your trays.',
  'Iniciando...': 'Starting...', 'Pedir investigación': 'Start research', 'Cancelar': 'Cancel',
  '¿Qué te frena? (Investigar)': 'What is holding you back? (Research)',
  'Volver a las bandejas': 'Back to your trays', 'Al volver, conservas el avance. Las otras bandejas esperan.': 'Your progress stays with you. The other trays can wait.',
  '1. Formular pregunta': '1. Frame the question', '2. Búsqueda web': '2. Search the web',
  '3. Detectar lagunas': '3. Find missing information', '4. Búsqueda de seguimiento': '4. Follow-up search', '5. Guía respaldada': '5. Source-backed guide',
  'No se confirmó la aceptación. No se enviará otra ejecución automáticamente.': 'Acceptance is unconfirmed. Another run will not be sent automatically.',
  'No se confirmó el envío. Tu investigación se conserva; no hemos creado otra.': 'Submission is unconfirmed. Your research is saved; no new run was created.',
  'Consultando tu investigación…': 'Loading your research…', 'Investigación de apoyo': 'Research support',
  'El resultado anterior se conserva.': 'The previous result is preserved.',
  'La entrega al ejecutor no está confirmada. Conservamos esta investigación; requiere revisión operativa antes de reenviarla.': 'Delivery to the worker is unconfirmed. This research is saved and needs an operational check before it can be sent again.',
  'Comprobando…': 'Checking…', 'Reanudar investigación': 'Resume research', 'Fuentes y guía': 'Sources and guide',
  'Entrega por confirmar': 'Delivery unconfirmed', 'Investigando fuentes…': 'Researching sources…',
  'Listo para revisión': 'Ready for review', 'Pausada por error': 'Paused after an error', 'Retomando un paso': 'Recovering a step',
  'Paso «': 'Step “', '» en auto-recuperación (Intento': '” is recovering automatically (attempt',
  'Un intento previo tuvo un corte o demora. Los pasos ya guardados se conservan.': 'An earlier attempt was interrupted or delayed. Saved steps are preserved.',
  'Puedes volver a tus bandejas o bloquear el teléfono. La investigación sigue por su cuenta; al volver consultaremos el resultado guardado.': 'You can return to your trays or lock your phone. Research continues in the background; when you return, we will load the saved result.',
  'Etapas de investigación': 'Research stages', 'Preguntas en indagación activa:': 'Questions being investigated:',
  'Guía de acción respaldada con fuentes': 'An action guide backed by sources',
  'Paso añadido a tu bandeja': 'Step added to your tray', 'Convertir este paso en una tarea de tu bandeja': 'Turn this step into a task in your tray',
  'Añadido': 'Added', 'A la bandeja': 'Add to tray', 'Fuentes citadas:': 'Sources:',
  'Sin confirmar con fuentes fidedignas': 'Not confirmed by reliable sources',
  'Lo que la investigación no logró corroborar plenamente en las fuentes encontradas. No es un fallo: es la diferencia entre informar con rigor y adivinar. Tómalo con criterio propio:': 'The available sources did not fully confirm these points. Review them carefully before acting:',
  'Contradicción detectada entre fuentes': 'Sources disagree', 'Transparencia Documental': 'Source transparency',
  'Esto no me cuadra (contradicción detectada entre fuentes):': 'These sources disagree:',
  'Domi no toma partido a ciegas: te mostramos la discrepancia para que decidas con los hechos verificados.': 'Domi shows the disagreement so you can decide using the verified facts.',
  'Ver las': 'View all', 'fuentes consultadas durante el proceso': 'sources consulted during research', 'Consulta': 'Search',
  'La investigación no pudo completarse. Tu tarea, notas y resultados guardados se conservan.': 'Research could not finish. Your task, notes, and saved results are preserved.',
  'Referencia:': 'Reference:', 'Investigación pausada': 'Research paused', 'Toca para revisar el estado': 'Open to check the status',
  'Ver guía fundamentada y fuentes de la investigación': 'View the source-backed guide and research sources',
  'Investigación lista para revisión': 'Research ready for review', 'Abrir': 'Open', 'Hallazgos listos': 'Findings ready',
  ' · 1 contradicción detectada': ' · 1 source disagreement', 'Averiguando fuentes con Linkup': 'Finding sources with Linkup',
  'Puedes seguir ordenando tareas o salir. Al terminar te avisamos aquí.': 'Keep organizing your tasks or leave. Your result will appear here when ready.',
  'Investigación ·': 'Research ·', 'Un espacio para aclarar': 'Room to find answers',
  'Revisa las fuentes a tu ritmo. Tú decides qué hacer con lo encontrado.': 'Review the sources at your own pace. You decide what to do with the findings.',
  'Abriendo tu mesa…': 'Opening your desk…',
  'El navegador no pudo guardar el avance. Mantén esta pestaña abierta.': 'Your browser could not save progress. Keep this tab open.',
  'Hay una sesión guardada que no se pudo leer. No se ha sobrescrito; esta sesión será temporal.': 'A saved session could not be read. It has not been overwritten; this session is temporary.',
  'El almacenamiento está bloqueado. Puedes usar DOMI sin cerrar esta pestaña.': 'Storage is blocked. You can use Domi while keeping this tab open.',
  'Esta investigación no está disponible con la sesión de este navegador.': 'This research is not available in this browser session.',
  'Se alcanzó el límite de consultas. Esperaremos antes de volver a leer.': 'The read limit was reached. We will wait before checking again.',
  'No pudimos actualizar la investigación. Volveremos a consultar.': 'We could not update the research. We will check again.',
  'La respuesta no corresponde a esta investigación.': 'The response does not match this research.',
  'La conexión está tardando. Volveremos a consultar.': 'The connection is taking a while. We will check again.',
  'El servicio no está disponible en este momento.': 'The service is unavailable right now.',
  'paso fundamentado': 'source-backed step',
  'pasos fundamentados': 'source-backed steps',
  'minuto': 'minute',
  'minutos': 'minutes',
  'segundo': 'second',
  'segundos': 'seconds',
  'registrados': 'logged',
  'y': 'and',
  'Mover': 'Move',
  'a otra bandeja': 'to another tray',
  'pendientes': 'tasks',
  'pendiente': 'task',
  'Visible': 'Visible',
  'Bandeja': 'Tray',
}
export function translate(locale: Locale, text: string): string {
  return locale === 'en' ? EN[text] ?? text : text
}
